language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master
    - "/v[0-9]+\\.[0-9]+-release$/"

before_deploy:
  - mvn clean package -DskipTests
  - export APP_RELEASE_FILE=$(find rbs-test-app/target -regex '.*/rbs-test-app-[0-9]+\.[0-9]+\.jar')
  - export APP_SOURCES_FILE=$(find rbs-test-app/target -regex '.*/.*[0-9]+\.[0-9]+-sources\.jar')
  - export APP_JAVADOC_FILE=$(find rbs-test-app/target -regex '.*/.*[0-9]+\.[0-9]+-javadoc\.jar')

deploy:
  provider: releases
  api_key:
    secure: l82dwhmW5w3Ie38BCJEfSiDKEAAtw95BliUh/Kd6YosXemWDGXBtRtbzlno0sqQQewCvWmbPQS47R4rzLq0ANyHdBMUA+WvX90s9gGynQh3xu601uBfWsfWegaSo2fiLCVfwHb0ftgbTVMf5xe+OnJIwHyQ6NfnD/BhujAudmV3Wch1NZfLqzjf7ly6XjTEBmEKmed5MY0Mc9NWLPQ/V6kdt2TyAn9wjBvhq3LXZW8XN9us5Uuzvaanh4dVrjUh0JbLl2qa3Rh3DL/sPKRPDrvxptNKqmxsmerohFNZGCuSk2BLSh/2U5OJ+7dssglPcYp3Ci5Hcb1aYZ5w/8DFBZ1j8o62pPlEDNq8XfTBscwoBy3xWtl5lpDHqUUWj0h7yTBBPM+P+gPz347qnNuQyf24X4TI3ny5RCkYRA2y2AUk1N2kdli9NT/4CS1CCSO9W3iaDlC7R9qxDPZYw2WvG/Cp9T4YRV5OFYMPjFZ7UM+4tFs9Cl+0ewHLDiVYoUmoHV2hgEVOGOZXTsVu2ZdbKnBxbFgWgWRb86KW4XHhHy5IG+FUsJpH3TT1zOWksNpdLb4hDcRRRzleRKHHSArxiHfgeFhXk1FGzHKH23695CPEkWtK4QTCctOcIIEeSyohZtRYnTzW+BDxC2SGvdRmauEqr/uLtoZhLOFGR9UZV5Xs=
  file:
    - "${APP_RELEASE_FILE}"
    - "${APP_SOURCES_FILE}"
    - "${APP_JAVADOC_FILE}"
  skip_cleanup: true
  on:
    repo: lukaswerner/RoleBasedSecurity
    tags: true
    all_branches: true
